
import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { Zap } from "lucide-react";
import { motion } from "framer-motion";

// Sample prediction data - in a real implementation this would be generated by AI
const predictionData = [
  { day: 'Day 1', actual: 25, predicted: 25 },
  { day: 'Day 2', actual: 32, predicted: 30 },
  { day: 'Day 3', actual: 35, predicted: 37 },
  { day: 'Day 4', actual: 40, predicted: 42 },
  { day: 'Day 5', actual: 50, predicted: 48 },
  { day: 'Day 6', actual: null, predicted: 55 },
  { day: 'Day 7', actual: null, predicted: 63 },
  { day: 'Day 8', actual: null, predicted: 68 },
  { day: 'Day 9', actual: null, predicted: 72 },
  { day: 'Day 10', actual: null, predicted: 75 },
];

const habitInsights = [
  "You're 85% likely to reach your weekly goal based on current progress",
  "Your most productive time is between 9-11 AM",
  "You complete 30% more tasks when you start your day with exercise",
  "Weekend consistency has improved by 40% this month"
];

const HabitForecast = () => {
  return (
    <Card>
      <CardHeader className="bg-primary/5">
        <CardTitle className="flex items-center gap-2">
          <Zap className="h-5 w-5 text-primary" />
          AI Habit Forecast
        </CardTitle>
      </CardHeader>
      <CardContent className="p-4 pt-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="mb-6 h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={predictionData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#888" strokeOpacity={0.2} />
                <XAxis dataKey="day" stroke="#888" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#888" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `${value}`} />
                <Tooltip />
                <Legend />
                <Line 
                  type="monotone" 
                  dataKey="actual" 
                  stroke="#3b82f6" 
                  strokeWidth={2} 
                  dot={{ r: 4 }}
                  name="Actual Points"
                />
                <Line 
                  type="monotone" 
                  dataKey="predicted" 
                  stroke="#10b981" 
                  strokeWidth={2} 
                  strokeDasharray="5 5"
                  dot={{ r: 4 }} 
                  name="AI Prediction"
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        <div className="space-y-3">
          <h3 className="text-sm font-medium">AI Insights:</h3>
          <div className="grid gap-2">
            {habitInsights.map((insight, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.3, delay: index * 0.1 }}
                className="flex items-center gap-2 p-2 text-sm border rounded-md bg-background"
              >
                <div className="flex-shrink-0 w-5 h-5 flex items-center justify-center bg-primary/10 rounded-full">
                  <Zap className="h-3 w-3 text-primary" />
                </div>
                <p>{insight}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default HabitForecast;
